72 設計tokenize変更のよるparseの見直し
s1-haya/minishell_bonus pull request #93
Opened 2023-08-08 01:28 UTC by taka-chin

メンバ変数とメンバ関数のまとめ修正しました
確認お願いします

2023-08-08 04:59 UTC, YungTatyu reviewed
コメントを参考に修正箇所は修正願います。

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +t_ast *ast_parse(t_token **token_adress, t_data *d)
大元の関数名は、parse()でいいと思います。
参考までに、以下が他のモジュールの大元の関数名です。
tokenize
command_execution

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
>        		left_node = ast_make_ast_ope(type, left_node, ast_command(token));
コマンドノードを作る関数がast_commandになっています。
それと同様に関数名を統一するといいと思います。
ast_make_ast_ope() -> ast_operator()

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +  if (token->word[0] == '(')//怪しい
()の対応も確定したいので、参考にしている記事をもう一度目を通すといいかもしれません。
expect()関数の中身も気になります。

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> -	syntax_error();
syntax_error関数の中身も気になります。
命名規則は、ast_syntax_errorになるでしょうか？

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +		node->command_list->fd_type = STDOUT;
fd_typeは削除してください。

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> -t_ast *ast_command(t_token **token)
基本的に引数でtokenを渡す場合、ダブルポインタでtoken_addressを渡さないといけないです。
引数でtokenを渡している場合は、token_addressにすべて変更する必要があると思います。
なので以下に統一しましょう；）
・token_address（ダブルポインタ）
・token（シングルポインタ）

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
>  	ast_ope -> command_list = NULL;
callocを使っているので、NULLで初期化する処理は省略できます。

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +	node = (t_ast*)malloc(sizeof(t_ast)*1);
try_callocを使って、NULLで初期化する処理を省力してもいいかもしれません。
（mustでないので、参考程度に）

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +t_ast *ast_init_node(t_token **token_adress)
この関数はどこからも呼び出されていないように見えます。
必要ないならば削除していいと思います。

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +void ast_add_back_ast_node(t_ast **head, t_ast *new_node)
ast_add_back_ast_node ()
関数名ですが、以下でもいいかもしれません。（参考程度に）
ast_addback ()

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +	node = ast_init_word_word_node(node);
ast_init_word_word_node ()
関数名ですが、wordが一つ多いですか？

2023-08-08 04:59 UTC, YungTatyu commented on includes/parse.c
> +	set_redirect_type(token);//redirectタイプをsetする関数
set_redirect_type
redirect_wordのタイプを設定するので、
set_redirect_word_type()の方がいいと思います。

2023-08-08 05:51 UTC, s1-haya reviewed
設計ありがとうございました！以下は質問です！

2023-08-08 05:51 UTC, s1-haya commented on includes/parse.c
> -t_ast *ast_command(t_token **token)
ダブルポインタの場合は変数名に*_addressをつけるのトークンでもやっていなかったのですが統一しますか？？

統一する場合は以下のようになりますか？？
変更前　head（ダブルポインタ）
変更後　token_address（ダブルポインタ）

2023-08-08 05:51 UTC, s1-haya commented on includes/parse.c
> -t_ast *ast_init_node(t_token **token_adress)
引数にtoken_adressのダブルポインタは入りますか？

nodeを初期化するだけの関数だったら必要ないと思いました！

2023-08-08 08:37 UTC, taka-chin commented on includes/parse.c
> +t_ast *ast_parse(t_token **token_adress, t_data *d)
修正しました

2023-08-08 08:49 UTC, taka-chin commented on includes/parse.c
>        		left_node = ast_make_ast_ope(type, left_node, ast_command(token));
ast_operator()に修正します

2023-08-08 08:51 UTC, taka-chin commented on includes/parse.c
> +  if (token->word[0] == '(')//怪しい
この怪しいは自分の理解が怪しいってことなのでコメントは消して参考記事を見直します

2023-08-08 08:57 UTC, taka-chin commented on includes/parse.c
> -	syntax_error();
命名規則はastをつけます
ast_syntax_error()の中身は要相談

2023-08-08 08:59 UTC, taka-chin commented on includes/parse.c
> +		node->command_list->fd_type = STDOUT;
fd_typeを削除しました

2023-08-08 09:03 UTC, taka-chin commented on includes/parse.c
> +	node = (t_ast*)malloc(sizeof(t_ast)*1);
mallocはtry_callocに修正しました

2023-08-08 09:17 UTC, taka-chin commented on includes/parse.c
> +t_ast *ast_init_node(t_token **token_adress)
t_ast *ast_command()で領域確保する必要があるのでここで使用することにしました

2023-08-08 09:39 UTC, taka-chin commented on includes/parse.c
> +	node = ast_init_word_word_node(node);
ast_init_word_node()に修正しました

2023-08-08 09:47 UTC, taka-chin commented on includes/parse.c
> +	set_redirect_type(token);//redirectタイプをsetする関数
set_redirect_word_type()に変更しました

2023-08-08 09:48 UTC, taka-chin commented on includes/parse.c
> -t_ast *ast_init_node(t_token **token_adress)
> さっき気づいたのですがt_wordの構造体は削除した方がいいと思いました！
> t_word_list *ast_init_word_node(t_word *word);
> void *ast_add_back_word_list(t_word **head,t_word *node);

t_word をt_word_listに変更しました

2023-08-08 09:49 UTC, taka-chin commented on includes/parse.c
> -t_ast *ast_init_node(t_token **token_adress)
> ダブルポインタの場合は変数名に*_addressをつけるのトークンでもやっていなかったのですが統一しますか？？
> 
> 統一する場合は以下のようになりますか？？
> 変更前　head（ダブルポインタ）
> 変更後　token_address（ダブルポインタ）

要相談

2023-08-08 09:52 UTC, taka-chin commented on includes/parse.c
> -t_ast *ast_init_node(t_token **token_adress)
> 引数にtoken_adressのダブルポインタは入りますか？
> 
> nodeを初期化するだけの関数だったら必要ないと思いました！

いらないと思うので消しました

2023-08-08 11:10 UTC, taka-chin commented on includes/parse.c
> +void ast_add_back_ast_node(t_ast **head, t_ast *new_node)
ast_addback();//構造体の型の名前を先頭につける
word_addback();//

2023-08-09 02:58 UTC, taka-chin commented
指摘事項の反映を行いました。確認お願いします。

2023-08-09 04:47 UTC, YungTatyu reviewed
修正有難うございます。
命名規則の修正が一部のみになってしまっている印象を受けました。
全体的に見直して、修正願います。

2023-08-09 04:47 UTC, YungTatyu commented on includes/parse.c
> +t_ast *ast_parse(t_token **current_token, t_data *d)
命名規則が修正されていない点が見受けれます。
以下は例です。
・ast_parse() →parse()
・ast_make_ast_ope() → ast_operator()
・is_opereter ()
・syntax_error ()
・引数で、tokenを渡すときは、current_tokenを直接渡すか、&tokenで渡すの二択

他にもあると思うので、全体的に命名規則を統一お願いします。
関数名を修正する際は、検索をかけて、一度にすべて修正すると、問題は解決するかと思います。

2023-08-09 04:47 UTC, YungTatyu commented on includes/parse.c
> +  if (current_token->word[0] == '(')//怪しい
tokenはダブルポインタで取得しているので、アクセスの仕方に工夫がいります。
以下のように、アクセスできません。
`current_token->word[0]`
以下の二通りの解決法があると思います。
・1
```
t_token *token = *current_token;
token->word[0]
```

・２
`(*current_token)->word[0]`

2023-08-09 04:47 UTC, YungTatyu commented on includes/parse.c
> +	add_back_redirect_list(redirect_list,node);
命名規則は以下のようになると思います。
ast_init_redirect_node() → redirect_init()
add_back_redirect_list() → redirect_addback()

2023-08-09 04:47 UTC, YungTatyu commented on includes/parse.c
> +	set_word(node->word);
命名規則は以下のようになります。
set_word() → redirect_set_word()
set_redirect_type() → redirect_set_type()

2023-08-09 07:22 UTC, s1-haya reviewed
設計ありがとがとうございます！以下が気になった点です！！

parse.cをparseディレクトリの方に入れといてもらえると助かります！！

2023-08-09 07:22 UTC, s1-haya commented on includes/parse.c
> +void word_list_addback(t_word **head,t_word *node);
変更前　t_word
変更後　t_word_list

2023-08-09 10:18 UTC, taka-chin commented on includes/parse.c
> +  if (current_token->word[0] == '(')//怪しい
1.の書き方で統一します

2023-08-09 10:19 UTC, taka-chin commented on includes/parse.c
> +	add_back_redirect_list(redirect_list,node);
修正しておきます

2023-08-09 10:20 UTC, taka-chin commented on includes/parse.c
> +	set_word(node->word);
修正します

2023-08-09 10:22 UTC, taka-chin commented on includes/parse.c
> +void word_list_addback(t_word **head,t_word *node);
修正しておきます

2023-08-09 10:22 UTC, taka-chin commented on includes/parse.c
> +bool is_opereter(e_ast_type type)
修正しておきます

2023-08-09 10:29 UTC, taka-chin commented on includes/parse.c
> +		syntax_error();
syntax_error()自体はエラーメッセージを出力するくらいだと思っていますが
syntax_errorがあった場合、heardocで判断する変数が必要になるかもしれません
要相談

2023-08-12 06:37 UTC, taka-chin commented
指摘事項反映しました
再度レビューお願いします

2023-08-12 07:44 UTC, s1-haya reviewed
以下よろしくお願いします！！

2023-08-12 07:44 UTC, s1-haya commented on includes/parse.c
> +			token = token->next; //
ast_commandの方でtokenをnextしてるみたいなので最後のtoken = token->nextするのは不要だと思います！

ast_commandがsyntax_errorの時に処理を終了してleft_nodeを出力したいのでそうなるような実装お願いします！！

2023-08-12 07:44 UTC, s1-haya commented on includes/parse.c
> +			command_ridirect_list(&(command_node->command_list->redirect_list),
command_ridirect_list-> command_redirect_list

2023-08-12 07:44 UTC, s1-haya commented on includes/parse.c
> +void	command_word_list(t_word_list *word_list, t_token *token)
この関数はheadにtokenを追加する関数みたいなのでt_word_list **headダブルポインタがいいと思います！

2023-08-12 07:44 UTC, s1-haya commented on includes/parse.c
> +}
t_ast型でsyntax_errorの際はNULLを出力する関数

2023-08-12 07:54 UTC, YungTatyu commented on includes/bk_parse.h
> +	bool 	is_ambiguas_error;//初期値はfalse
is_ambiguas_error のスペルが気になりました。
正しくは、ambiguous

2023-08-12 07:54 UTC, YungTatyu commented on includes/bk_parse.h
> +t_ast *ast_command(t_token *token,t_data *d);
以下の関数で引数の名前がtokenのままです。

・command_word_list
・ast_command
・word_list_init
・redirect_init
・ast_expect

2023-08-12 07:54 UTC, YungTatyu commented on includes/parse.c
> +		error("'%c'ではありません", op);
error関数はast_syntax_error()と違う内容ですか？

2023-08-12 09:44 UTC, taka-chin commented on includes/parse.c
> +			token = token->next; //
d->syntax_flagをチェックしその時のastを返す処理を追加しました

2023-08-12 09:45 UTC, taka-chin commented on includes/parse.c
> +			command_ridirect_list(&(command_node->command_list->redirect_list),
修正しました

2023-08-12 09:46 UTC, taka-chin commented on includes/parse.c
> +void	command_word_list(t_word_list *word_list, t_token *token)
headに修正しました

2023-08-12 09:51 UTC, taka-chin commented on includes/parse.c
> +}
型はvoidにして204行目からをコメントアウトしました

2023-08-12 09:52 UTC, taka-chin commented on includes/bk_parse.h
> +	bool 	is_ambiguas_error;//初期値はfalse
修正しました

2023-08-12 11:21 UTC, taka-chin commented on includes/bk_parse.h
> +t_ast *ast_command(t_token *token,t_data *d);
修正しました

2023-08-12 11:54 UTC, taka-chin commented on includes/parse.c
> +		error("'%c'ではありません", op);
error関数はsyntax_errorに変更します

2023-08-12 11:55 UTC, taka-chin commented
指摘事項を修正しました
確認お願いします！

2023-08-12 13:40 UTC, s1-haya requested changes

2023-08-12 13:40 UTC, s1-haya commented on includes/parse.c
>  }
if 文の中にd->syntax_flag入れても大丈夫だと思います！

```
while (true)
{
		if (token == null || !ast_is_operator(token->type) || d->syntax_flag)
                        break;
		type = token->type;
		token = token->next; //operatarのtoken
		left_node = ast_operator_node(type, left_node, ast_command_node(token, d));
}
return (left_node);
```

2023-08-13 04:49 UTC, YungTatyu reviewed
設計ありがとうございます。
全体的な設計は良いと思いました。

2023-08-13 04:49 UTC, YungTatyu commented on includes/parse.h
> +bool					command_is_redirect(t_token type);
command_is_redirect()
上記ですが、tokenを見ているなら、以下の名前になるのでしょうか？
token_is_redirect()
(参考程度にコメント残しました)

2023-08-13 04:49 UTC, YungTatyu commented on includes/parse.c
> +	d->exit_status = hogehoge;
syntax_errorのexit_statusは設計の時点で、調査したほうが良いと思いました。

2023-08-13 04:49 UTC, YungTatyu commented on includes/parse.c
> +	d->syntax_flag = 1;
個人的にsyntax_flagはtrue, falseでもって頂いたら嬉しいです。

2023-08-13 05:52 UTC, taka-chin commented on includes/parse.c
> +	d->exit_status = hogehoge;
exit_statusは258にします？

2023-08-13 05:52 UTC, taka-chin commented on includes/parse.c
> +	d->syntax_flag = 1;
syntan_flagはtrueにします

2023-08-14 06:51 UTC, taka-chin commented on includes/parse.h
> +bool					command_is_redirect(t_token type);
token_is_redirectに修正しました

2023-08-14 06:52 UTC, taka-chin commented on includes/parse.c
>  }
syntax_error周りの見直しとright_nodeの実装をしました

2023-08-14 07:18 UTC, taka-chin commented
syntax_error周辺の実装と指摘事項の反映を行いました
確認お願いします

2023-08-14 08:09 UTC, YungTatyu approved these changes

2023-08-14 08:09 UTC, YungTatyu commented on includes/parse.c
> +			if(d->syntax_flag)
if(d->syntax_flag)
上記の条件式は一つにまとめることができます。
複数書く必要なし。

2023-08-14 08:47 UTC, s1-haya approved these changes
いいと思います！

2023-08-14 08:48 UTC, merged