70 設計 expansionのメンバ変数とメンバ関数基本的流れ
s1-haya/minishell_bonus pull request #97
Opened 2023-08-12 06:58 UTC by s1-haya

2023-08-12 08:32 UTC, YungTatyu commented on includes/expansion.h
> +
t_data **dはいかに修正できます。
t_data *d

2023-08-12 08:32 UTC, YungTatyu commented on srcs/expansion/expand_variable.c
> +	t_word_list		*ite;
細かいですが、変数名iteはiteratorですか？
nodeでも良いかと思いました。
（参考程度で大丈夫です）

2023-08-12 08:32 UTC, YungTatyu commented on srcs/expansion/expand_variable.c
> +		expand_word = expand_get_expand_word(word, d->envs_hashmap);
実装するときの話になりますが、環境変数の終わりの文字を調べる必要があります。
例えば、スペース、タブ以外にも多くの記号は環境変数の終わりと認識されます。

2023-08-12 08:32 UTC, YungTatyu commented on srcs/expansion/expand_word_splitting.c
> +	// IFSがデフォルトの場合
IFSに空白もしくはtabが含まれている場合、単語分割が行われます。

IFS='       abc'（空白とタブもしくはどちらかが含まれている）
上記のような場合、単語分割は行われます。
ft_strchr()の条件にタブも含む必要があります。

2023-08-12 08:32 UTC, YungTatyu commented on srcs/expansion/expand_delete_quote.c
> +
念のためにコメント残します。
クオテーションを削除した後に、クオテーションに囲まれているノードをすべてstrjoinする必要があります。

2023-08-12 08:32 UTC, YungTatyu commented on library/srcs/try/try_getcwd.c
> +main() {
try系の関数には、引数でt_data *dを渡す必要があります。
エラーが起きた場合、終了ステータスを更新するため。
例外としては、minishellを終了させる場合は（exitする）、dを渡す必要はないです。
今回の場合は、minishellを終了させないと思うので、dを引数に渡します。

2023-08-12 09:30 UTC, taka-chin requested changes
レビュー完了しました
指摘事項の確認お願いします

2023-08-12 09:30 UTC, taka-chin commented on srcs/expansion/expand_variable.c
> +	if (word == '?')
word == '?'
ではなく**word == '?'でしょうか？

2023-08-12 09:30 UTC, taka-chin commented on srcs/expansion/expand_variable.c
> +	while (*token_word)
while(*token_word)はwhile(token_word)でしょうか？

2023-08-12 09:30 UTC, taka-chin commented on srcs/expansion/expand_word_splitting.c
> +	return (word);
型が違うかも〜
return(*word)?

2023-08-12 09:30 UTC, taka-chin commented on srcs/expansion/expansion.c
> +	return (0);
関数の型が違うかも〜
void → int？

2023-08-12 09:48 UTC, s1-haya commented on srcs/expansion/expand_variable.c
> +		expand_word = expand_get_expand_word(word, d->envs_hashmap);
exportが登録できない文字の場合は区切り文字にする必要がある。

2023-08-13 07:19 UTC, YungTatyu reviewed
設計ありがとうございます。
気になる点はコメント残しました。

2023-08-13 07:30 UTC, s1-haya commented on srcs/expansion/expand_variable.c
> +{
ありがとうございます！考慮します！

2023-08-13 08:35 UTC, taka-chin reviewed
レビューしました
確認お願いします

2023-08-13 08:49 UTC, s1-haya reviewed
いいと思います！

2023-08-13 09:07 UTC, merged